# taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

# brews
brew "docker"

# casks
cask "alacritty"
cask "brave-browser"
cask "bruno"
cask "dbeaver-community"
cask "firefox"
cask "spaceman"
cask "spotify"
cask "tunnelblick"
cask "hiddenbar"
